stages:
  - mirror

mirror_to_github:
  stage: mirror
  script:
    - git remote add github https://trustcaptcha:${GITHUB_ACCESS_TOKEN}@github.com/trustcaptcha/php-library.git
    - git push --mirror github
  only:
    - tags
  tags:
    - build
