stages:
  - mirror

mirror_to_github:
  stage: mirror
  script:
    - git remote | grep -q github || git remote add github https://trustcaptcha:${GITHUB_ACCESS_TOKEN}@github.com/trustcaptcha/php-library.git
    - git push github 'refs/heads/*:refs/heads/*' --force
    - git push --tags github --force
  only:
    - tags
  tags:
    - build
