stages:
  - mirror

mirror_to_github:
  stage: mirror
  script:
    - git remote | grep -q github || git remote add github https://trustcaptcha:${GITHUB_ACCESS_TOKEN}@github.com/trustcaptcha/php-library.git
    - git push --tags github 'refs/heads/*:refs/heads/*'
    - git push --tags github 'refs/tags/*:refs/tags/*'
  only:
    - tags
  tags:
    - build
